# Generated by Django 6.0.2 on 2026-02-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_author_instagram_author_telegram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#99E3AD', max_length=7),
        ),
    ]
