"""
Django settings for news project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ob@u9&evz8-&+4q9xx$tdq(xro=+p!rwo1a+d9o@d#&e(%$l$e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'django.contrib.sites',
    'django.contrib.flatpages',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.yandex',

    'simpleapp',
    'portal.apps.PortalConfig',
    'django_filters',
    'sign',
    'django_apscheduler',
]

SITE_ID = 2

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'news.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'portal.context_processors.categories_processor',
            ],
        },
    },
]

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


import os

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR / 'media')
WSGI_APPLICATION = 'news.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_RATE_LIMITS = {
    'login_failed': '5/5m'
}

# работает подтверждение почты, чтобы пользователь получал письмо с активацией
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
# доп. опция: перейти по ссылке сразу подтверждает
ACCOUNT_CONFIRM_EMAIL_ON_GET = True


ACCOUNT_FORMS = {
    'signup': 'sign.forms.CommonSignupForm',
}

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SOCIALACCOUNT_PROVIDERS = {
    'yandex': {}
}

DEFAULT_FROM_EMAIL = 'noreply@newsportal.com'




import os
from dotenv import load_dotenv

# Загружаем переменные из .env
load_dotenv()

EMAIL_PROVIDER = os.getenv("EMAIL_PROVIDER", "gmail").lower()

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

if EMAIL_PROVIDER == "gmail":
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.getenv("GMAIL_EMAIL_USER")
    EMAIL_HOST_PASSWORD = os.getenv("GMAIL_EMAIL_PASSWORD")

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Временная проверка (удалены печатные сообщения, чтобы не засорять логи воркеров)
# Для отладки используйте логирование или django-admin shell

# APScheduler configuration
APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"
APSCHEDULER_RUN_NOW_TIMEOUT = 25  # Seconds

# Celery Configuration
CELERY_BROKER_URL = os.getenv(
    'CELERY_BROKER_URL',
    'redis://:RaOHBEYoA7dn0UTV6mfJlTEh0UhSXptV@redis-13497.c62.us-east-1-4.ec2.cloud.redislabs.com:13497/0',
)
CELERY_RESULT_BACKEND = os.getenv(
    'CELERY_RESULT_BACKEND',
    CELERY_BROKER_URL,
)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Celery Beat Schedule задается в news/celery.py через crontab.

# APScheduler fallback: отключен weekly digest по умолчанию,
# чтобы избежать двойной рассылки вместе с Celery Beat.
APSCHEDULER_ENABLE_WEEKLY_DIGEST = os.getenv(
    'APSCHEDULER_ENABLE_WEEKLY_DIGEST',
    '0',
) in {'1', 'true', 'True'}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


